name: CI Test pipeline

on:
  push:
    branches:
      - main
    paths:
      - project/**

jobs:
  test-CI:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: main

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r project/requirements.txt

      - name: run test
        run: |
          chmod +x ./project/tests.sh
          ./project/tests.sh